# See LICENSE file for copyright and license details.

MAN=

beforeinstall:
	${INSTALL} ${INSTALL_COPY} -o ${BINOWN} -g ${BINGRP} -m ${BINMODE} \
		${.CURDIR}/../netpref-new.sh ${DESTDIR}${BINDIR}/netpref-new

.include <bsd.prog.mk>
