.\" See LICENSE file for copyright and license details.
.Dd $Mdocdate: Feb 14 2015$
.Dt AUTONET 1
.Os
.Sh NAME
.Nm autonet
.Nd automatically connect to a known wifi network
.Sh SYNOPSIS
.Nm
.Op Fl s
.Op Fl v
.Oo
.Fl x Ar excluded_profile
.Op Fl x Ar ...
.Ar ...
.Oc
.Sh DESCRIPTION
.Nm
brings up the configured wireless interface, scans for networks,
and connects to the best match among previously configured known
profiles.
.Pp
.Nm
creates or resets a symlink from
.\" TODO: better format
.Pa /etc/hostname.<ifname>
to the best matching
.Pa /etc/hostname.d
entry (described below) it found in its scan. Then, it
execs
.Xr netstart 8
for
.Ar ifname .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl s
Just scan and create the symlink; don't run
.Xr netstart 8 .
This might be used to insert a call to
.Nm
prior to the systemwide
.Xr netstart 8
in
.Xr rc 8 .
.It Fl v
Print the version and exit.
.It Fl x Ar excluded_profile
Don't try to connect to the named profile, even if it shows up in
the scan.
.El
.Pp
Multiple profiles may be passed with
.Fl x
to exclude more than one profile.
.Pp
There are some things
.Nm
intentionally doesn't do:
.Bl -dash
.It
It doesn't provide any mechanism for discovery of unknown networks \(em
.Xr ifconfig 8
.Ap s scan command works just fine for that.
.It
It doesn't use any resources monitoring the connection status; it
runs once, synchronusly, and exits 0 when you're connected. If you
want to maintain a connection while you're away, it's easy enough
to write a script that calls
.Nm
when it detects that your network is down.
.El
.Sh CONFIGURATION
For each profile named in
.Nm
.Ap
s
.Pa config.h ,
there should be a
.Sm off
.Xr hostname.if 5
-formatted
.Sm on
file at
.Pa /etc/hostname.d/<ifname>.<profile> .
.Nm
creates a link to one of these files when it finds a known profile.
For instance, if
.Nm
was configured for interface iwn0 with a profile named
.Dq mynetwork ,
then the
.Dq mynetwork
.Xr hostname.if 5
configuration file would be located at
.Pa /etc/hostname.d/iwn0.mynetwork ,
and if that profile matched at runtime,
.Nm
would construct the symlink
.Pa "/etc/hostname.iwn0"
->
.Pa hostname.d/iwn0.mynetwork .
.Pp
Note that
.Nm
doesn't try to parse
.Xr hostname.if 5
files at runtime; if the profile for
.Dq mynetwork
doesn't match with the configuration in
.Pa iwn0.mynetwork
(i.e., if
.Pa config.h
specifies a different nwid or bssid from the one configured in
.Sm off
.Pa iwn0.mynetwork
),
.Sm on
.Nm
won't notice this, and will happily create a symlink to a
probably-broken network profile if the nwid in
.Pa config.h
matches. It is your responsibility to ensure that your
.Pa config.h
lines up with your
.Pa hostname.d .
.Sm on
.Sh FILES
.Bl -tag -width "/etc/hostname.d/XXX.YYYYYY   "
.It Pa /etc/hostname.d/XXX.YYYYYY
Interface- and network-specific profiles.
.Sh EXIT STATUS
.Nm
exits 0 on success, 1 if any of its calls failed, and 2 if it found
no networks that matched a known profile.
.Sh SEE ALSO
.Xr hostname.if 5 ,
.Xr ifconfig 8 ,
.Xr netstart 8 ,
.Xr rc 8
.Sh AUTHORS
.Nm Steven Dee
.Ao
.Mt steve@smartercode.net
.Ac
